-- MySQL Script generated by MySQL Workbench
-- Mon Dec  4 16:10:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`spectacle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`spectacle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `date_venue` DATETIME NULL,
  `content` VARCHAR(255) NULL,
  `nb_tickets` INT NULL,
  `place` VARCHAR(255) NULL,
  `type` ENUM('stage', 'spectacle') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `name` VARCHAR(45) NULL,
  `nb_ticket` INT NULL,
  `date_add` DATETIME NULL,
  `spectacle_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_spectacle1_idx` (`spectacle_id` ASC),
  CONSTRAINT `fk_reservation_spectacle1`
    FOREIGN KEY (`spectacle_id`)
    REFERENCES `mydb`.`spectacle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`newsletter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`newsletter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`newsletterhtml`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`newsletterhtml` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livre_dor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livre_dor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT(1024) NULL,
  `author` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `title` VARCHAR(255) NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `picturecol` VARCHAR(45) NULL,
  `spectacle_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_picture_spectacle1_idx` (`spectacle_id` ASC),
  CONSTRAINT `fk_picture_spectacle1`
    FOREIGN KEY (`spectacle_id`)
    REFERENCES `mydb`.`spectacle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
